# Generated by Django 5.0.6 on 2024-05-31 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('dateOfBirth', models.DateField()),
                ('mobile', models.CharField(max_length=10)),
                ('email', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=255, null=True)),
                ('healthInsuranceNumber', models.CharField(blank=True, max_length=255, null=True)),
                ('startBiography', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
