# Generated by Django 5.0.6 on 2024-05-31 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=255)),
                ('patient_mobile', models.CharField(max_length=255)),
                ('patient_email', models.CharField(max_length=255)),
                ('patient_address', models.CharField(max_length=255)),
                ('patient_dob', models.DateField()),
                ('dateOfAppointment', models.DateField()),
                ('fromTime', models.TimeField()),
                ('toTime', models.TimeField()),
                ('doctor_id', models.IntegerField()),
                ('treatment', models.CharField(max_length=255)),
                ('note', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
